name: Build

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install ninja-build
        sudo apt-get install texlive*
    - name: Build
      run: |
        find . -iname '*.tex' -exec pdflatex {} \;
    - uses: actions/upload-artifact@v4
      with:
        name: pdf-linux
        path: '*.pdf'
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup environment
      run: |
        brew install --cask mactex
    - name: Build
      run: |
        eval "$(/usr/libexec/path_helper)"
        find . -iname '*.tex' -exec pdflatex {} \;
    - uses: actions/upload-artifact@v4
      with:
        name: pdf-macos
        path: '*.pdf'
